package Cryptosystem;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;
  
public class SHA1 {
    public static String encryptThisString(String input)
    {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-1");
  
            byte[] messageDigest = md.digest(input.getBytes());

            BigInteger no = new BigInteger(1, messageDigest);
  
            String hashtext = no.toString(16);
  
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
  
            return hashtext;
        }
  
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
  
    public static void main(String args[]) throws NoSuchAlgorithmException
    {
    	Scanner sc = new Scanner(System.in);
        System.out.println("HashCode Generated by SHA-1 for: ");
		System.out.println("Enter the text: ");
        String s1 = sc.next();
        System.out.println("\n" + s1 + " : " + encryptThisString(s1));
  
    }
}
